import { AnimatePresence, motion } from 'motion/react';
import { useEffect, useRef, useState } from 'react';
import Icon from './Icon.jsx';
import StatusDot, { toneText } from './StatusDot.jsx';

const STAGES = [{ key: 'classify', label: 'CLASSIFY', provider: 'GROQ // LLAMA-3.1-8B' }, { key: 'enrich', label: 'ENRICH', provider: 'ABUSEIPDB + VIRUSTOTAL' }, { key: 'reason', label: 'REASON', provider: 'GEMINI-1.5-FLASH // RAG' }];
function CopyButton({ value, label, onCopy }) { return <button type="button" className="inline-flex items-center gap-1 text-[10px] text-ash transition-colors hover:text-amber" onClick={() => onCopy(value)}><Icon name="content_copy" size={13} /><span>{label}</span></button>; }
function SectionHeader({ label, open, onToggle, action }) { return <div className="flex items-center justify-between"><button type="button" className="drawer-section-toggle flex items-center gap-2 text-left" onClick={onToggle} aria-expanded={open}><Icon name={open ? 'expand_less' : 'expand_more'} size={15} className="text-amber" /><span className="eyebrow text-ash">{label}</span></button>{action}</div>; }

export default function AlertDetailDrawer({ alert, onClose }) {
  const closeRef = useRef(null);
  const [copied, setCopied] = useState('');
  const [openSections, setOpenSections] = useState({ route: true, pipeline: true, mitre: true, explanation: true, action: true });
  useEffect(() => { if (!alert) return undefined; closeRef.current?.focus(); const onKeyDown = (event) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [alert, onClose]);
  if (!alert) return null;
  const toggle = (key) => setOpenSections((current) => ({ ...current, [key]: !current[key] }));
  const copyValue = async (value) => { try { await navigator.clipboard?.writeText(value); setCopied(value); window.setTimeout(() => setCopied(''), 1400); } catch { setCopied('COPY UNAVAILABLE'); } };
  return <motion.aside className="drawer-enter fixed inset-y-0 right-0 z-50 flex w-full max-w-[var(--drawer-width)] flex-col border-l border-line-strong bg-ink-900 shadow-[-20px_0_50px_rgba(0,0,0,0.45)]" initial={{ x: '100%', opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: '100%', opacity: 0 }} transition={{ type: 'spring', stiffness: 260, damping: 28 }} aria-label="Alert evidence drawer"><div className="flex items-start justify-between border-b border-line-strong px-5 py-4"><div><div className="eyebrow mb-2">SIGNAL EVIDENCE // {alert.id}</div><h2 className="max-w-[300px] text-xl font-semibold leading-tight text-paper">{alert.attack_type?.replaceAll('_', ' ')}</h2><div className="mt-2 flex items-center gap-2 font-mono-ui text-[10px] text-ash"><StatusDot tone={alert.severity} pulse={alert.severity === 'critical'} />{alert.severity?.toUpperCase()} // {alert.protocol}:{alert.dest_port}</div></div><button ref={closeRef} type="button" className="ghost-button flex h-8 w-8 items-center justify-center" onClick={onClose} aria-label="Close evidence drawer"><Icon name="close" size={17} /></button></div><div className="flex-1 overflow-y-auto">
    <section className="drawer-section border-b border-line px-5 py-4" style={{ '--section-index': 0 }}><SectionHeader label="ROUTE" open={openSections.route} onToggle={() => toggle('route')} action={<div className="flex gap-3"><CopyButton value={alert.src_ip} label="COPY SRC" onCopy={copyValue} /><CopyButton value={alert.dest_ip} label="COPY DST" onCopy={copyValue} /></div>} /><AnimatePresence initial={false}>{openSections.route && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-center gap-3 font-mono-ui text-sm"><span className="truncate text-paper">{alert.src_ip}</span><span className="text-amber">→</span><span className="truncate text-right text-paper">{alert.dest_ip}</span></div><div className="mt-2 flex justify-between font-mono-ui text-[10px] text-ash-dark"><span>DEST PORT {alert.dest_port}</span><span>{alert.protocol}</span></div>{copied && <div className="mt-3 border-l-2 border-green bg-green/10 px-2 py-1 font-mono-ui text-[10px] text-green">{copied === 'COPY UNAVAILABLE' ? copied : 'COPIED TO CLIPBOARD'}</div>}</motion.div>}</AnimatePresence></section>
    <section className="drawer-section border-b border-line px-5 py-4" style={{ '--section-index': 1 }}><SectionHeader label="PIPELINE TRACE" open={openSections.pipeline} onToggle={() => toggle('pipeline')} /><AnimatePresence initial={false}>{openSections.pipeline && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="mt-4 overflow-hidden"><div className="space-y-0">{STAGES.map((stage, index) => { const complete = stage.key === 'classify' || (stage.key === 'enrich' && alert.ioc_checked) || (stage.key === 'reason' && alert.explanation); const latency = stage.key === 'classify' ? alert.classify_latency_ms : stage.key === 'enrich' ? alert.enrich_latency_ms : alert.reasoning_latency_ms; return <div key={stage.key} className="pipeline-stage relative flex gap-3 pb-4 last:pb-0" style={{ '--stage-index': index }} data-complete={complete}>{index < STAGES.length - 1 && <div className="absolute left-[5px] top-3 h-[calc(100%-5px)] w-px bg-line-strong" />}<span className={`relative z-10 mt-0.5 h-3 w-3 border ${complete ? 'border-amber bg-amber' : 'border-line-strong bg-ink-900'}`} /><div className="min-w-0 flex-1"><div className={`flex items-baseline justify-between font-mono-ui text-[11px] ${complete ? 'text-amber' : 'text-ash-dark'}`}><span>{stage.label}</span><span>{complete ? `${latency || 0}ms` : 'PENDING'}</span></div><div className="mt-1 text-[10px] text-ash-dark">{stage.provider}</div>{stage.key === 'enrich' && complete && <div className="mt-2 grid grid-cols-2 gap-2 font-mono-ui text-[10px]"><span className="border border-line-strong px-2 py-1 text-ash">ABUSE {alert.ioc_reputation}%</span><span className="border border-line-strong px-2 py-1 text-ash">VT {alert.vt_ip?.toUpperCase()}</span></div>}</div></div>; })}</div></motion.div>}</AnimatePresence></section>
    <section className="drawer-section border-b border-line px-5 py-4" style={{ '--section-index': 2 }}><SectionHeader label="MITRE ATT&CK / TECHNIQUE" open={openSections.mitre} onToggle={() => toggle('mitre')} /><AnimatePresence initial={false}>{openSections.mitre && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className={`mt-3 font-mono-ui text-lg font-semibold ${toneText(alert.severity)}`}>{alert.mitre_technique || 'UNMAPPED'}</div><p className="mt-2 text-xs leading-5 text-ash">The retrieved technique is used to ground the reasoning stage and prioritize the next analyst action.</p></motion.div>}</AnimatePresence></section>
    <section className="drawer-section border-b border-line px-5 py-4" style={{ '--section-index': 3 }}><SectionHeader label="AGENT LOG // EXPLANATION" open={openSections.explanation} onToggle={() => toggle('explanation')} /><AnimatePresence initial={false}>{openSections.explanation && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="mt-3 border border-line-strong bg-ink-950 p-3 font-mono-ui text-[11px] leading-5 text-ash"><span className="text-amber">// </span>{alert.explanation || 'Awaiting reason stage output.'}</div></motion.div>}</AnimatePresence></section>
    <section className="drawer-section px-5 py-4" style={{ '--section-index': 4 }}><SectionHeader label="RECOMMENDED ACTION" open={openSections.action} onToggle={() => toggle('action')} /><AnimatePresence initial={false}>{openSections.action && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><p className="mt-3 border-l-2 border-amber bg-amber/5 px-3 py-2 text-xs leading-5 text-paper">{alert.remediation || 'Maintain watch state and await additional evidence.'}</p><button type="button" className="terminal-button mt-4 inline-flex items-center gap-2 px-3 py-2 font-mono-ui text-[10px] uppercase tracking-[0.08em]" onClick={() => setCopied('ACTION QUEUED')}>Queue action <Icon name="arrow_forward" size={14} /></button></motion.div>}</AnimatePresence></section>
  </div></motion.aside>;
}
